######################################################################
# Automatically generated by qmake (2.01a) Thu Dec 19 13:48:07 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += client.hpp solution.hpp vue.hpp
FORMS += interface_graphique.ui
SOURCES += client.cpp main.cpp solution.cpp vue.cpp
